### ISSUE TITLE
Azure pipeline - use npm ci instead of npm install

### ISSUE THREAD

**Issue by benceHornyak** [Ethan-Arrowood/matterhorn#13]
For CI builds you should use [npm ci](https://docs.npmjs.com/cli/ci.html) command instead of npm install.

It is faster and it meant to be used inside CI jobs.

From npm blog:
https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

**Comment by Ethan-Arrowood** [comment]
Great idea! Want to send a PR?

**Comment by benceHornyak** [comment]
Yeah sure! I'm pretty busy atm, but will do around the end of the week

**Comment by Ethan-Arrowood** [comment]
Sounds good!
