### ISSUE TITLE
Can we integrate SWAGGER into it

### ISSUE THREAD

**Issue by panbhatt** [Ethan-Arrowood/matterhorn#22]
Can we integrate SWAGGER into it

**Comment by benceHornyak** [comment]
Yeah, I think so..
There is a plugin for it already: https://github.com/fastify/fastify-swagger

**Comment by panbhatt** [comment]
Yes, I had done it in my last project. 
Please let me know which branch to take the code from, I can commit it.

**Comment by Ethan-Arrowood** [comment]
Hello @panbhatt I think Swagger would be a great integration. Fork this repository and make your changes from a new branch created off of 'master'. When you're ready to share your changes open a pull request. Thank you for your interest in contributing! Let me know if you need any other assistance.

**Comment by panbhatt** [comment]
https://github.com/Ethan-Arrowood/matterhorn/pull/23 
Pull Request has been raised. Please review.

**Comment by panbhatt** [comment]
As per the latest build, npm run lint is failing.  and giving error that Fastify is never being used. 
Error:  2:13  error  'Fastify' is defined but never used  no-unused-vars

import * as FastifySwagger from 'fastify-swagger' 
import * as Fastify from 'fastify'
export  function configureSwagger(fastifyInstance: **Fastify.FastifyInstance** ) 

we have two Options npm run lint pass : (this is a known problem in typescript-eslint-parser).
[https://github.com/bradzacher/eslint-plugin-typescript/issues/112](https://github.com/bradzacher/eslint-plugin-typescript/issues/112)
[https://github.com/eslint/typescript-eslint-parser/issues/457 ](https://github.com/eslint/typescript-eslint-parser/issues/457 )
1.EIther make the type of FastifyInstance to Any. I do not think this is a good solution. 
2. Change the typescript lint rules as suggested in the above two likes. 

Please suggest what you thing is the most optimal way and I will go by that.

**Comment by panbhatt** [comment]
@Ethan-Arrowood  : Any update for me which way you want it to go.

**Comment by Ethan-Arrowood** [comment]
Tricky question @panbhatt I'm going to look into this and try to figure it out. I'll get back to you soon

**Comment by Ethan-Arrowood** [comment]
Okay I found a solution, check out the review comments I left on your PR. More feedback coming soon too!

**Comment by BugHiding** [comment]
https://github.com/facebook/jest/blob/c929ee3bc7c5d42ea0785003a72616c40556cc71/.eslintrc.js#L25
